INSERT INTO alternatif (id, nama) VALUES (1, 'Karyawan 1');
INSERT INTO alternatif (id, nama) VALUES (2, 'Karyawan 2');
INSERT INTO alternatif (id, nama) VALUES (3, 'Karyawan 3');
INSERT INTO alternatif (id, nama) VALUES (4, 'Karyawan 4');
INSERT INTO alternatif (id, nama) VALUES (5, 'Karyawan 5');
INSERT INTO alternatif (id, nama) VALUES (6, 'Karyawan 6');
INSERT INTO alternatif (id, nama) VALUES (7, 'Karyawan 7');
INSERT INTO alternatif (id, nama) VALUES (8, 'Karyawan 8');
INSERT INTO alternatif (id, nama) VALUES (9, 'Karyawan 9');
INSERT INTO alternatif (id, nama) VALUES (10, 'Karyawan 10');
INSERT INTO alternatif (id, nama) VALUES (11, 'Karyawan 11');
INSERT INTO alternatif (id, nama) VALUES (12, 'Karyawan 12');
INSERT INTO alternatif (id, nama) VALUES (13, 'Karyawan 13');
INSERT INTO alternatif (id, nama) VALUES (14, 'Karyawan 14');
INSERT INTO alternatif (id, nama) VALUES (15, 'Karyawan 15');
INSERT INTO alternatif (id, nama) VALUES (16, 'Karyawan 16');
INSERT INTO alternatif (id, nama) VALUES (17, 'Karyawan 17');
INSERT INTO alternatif (id, nama) VALUES (18, 'Karyawan 18');
INSERT INTO alternatif (id, nama) VALUES (19, 'Karyawan 19');
INSERT INTO alternatif (id, nama) VALUES (20, 'Karyawan 20');
INSERT INTO alternatif (id, nama) VALUES (21, 'Karyawan 21');
INSERT INTO alternatif (id, nama) VALUES (22, 'Karyawan 22');
INSERT INTO alternatif (id, nama) VALUES (23, 'Karyawan 23');
INSERT INTO alternatif (id, nama) VALUES (24, 'Karyawan 24');
INSERT INTO alternatif (id, nama) VALUES (25, 'Karyawan 25');
INSERT INTO alternatif (id, nama) VALUES (26, 'Karyawan 26');
INSERT INTO alternatif (id, nama) VALUES (27, 'Karyawan 27');
INSERT INTO alternatif (id, nama) VALUES (28, 'Karyawan 28');
INSERT INTO alternatif (id, nama) VALUES (29, 'Karyawan 29');
INSERT INTO alternatif (id, nama) VALUES (30, 'Karyawan 30');
INSERT INTO alternatif (id, nama) VALUES (31, 'Karyawan 31');
INSERT INTO alternatif (id, nama) VALUES (32, 'Karyawan 32');
INSERT INTO alternatif (id, nama) VALUES (33, 'Karyawan 33');
INSERT INTO alternatif (id, nama) VALUES (34, 'Karyawan 34');
INSERT INTO alternatif (id, nama) VALUES (35, 'Karyawan 35');
INSERT INTO alternatif (id, nama) VALUES (36, 'Karyawan 36');
INSERT INTO alternatif (id, nama) VALUES (37, 'Karyawan 37');
INSERT INTO alternatif (id, nama) VALUES (38, 'Karyawan 38');
INSERT INTO alternatif (id, nama) VALUES (39, 'Karyawan 39');
INSERT INTO alternatif (id, nama) VALUES (40, 'Karyawan 40');
INSERT INTO alternatif (id, nama) VALUES (41, 'Karyawan 41');
INSERT INTO alternatif (id, nama) VALUES (42, 'Karyawan 42');
INSERT INTO alternatif (id, nama) VALUES (43, 'Karyawan 43');
INSERT INTO alternatif (id, nama) VALUES (44, 'Karyawan 44');
INSERT INTO alternatif (id, nama) VALUES (45, 'Karyawan 45');
INSERT INTO alternatif (id, nama) VALUES (46, 'Karyawan 46');
INSERT INTO alternatif (id, nama) VALUES (47, 'Karyawan 47');
INSERT INTO alternatif (id, nama) VALUES (48, 'Karyawan 48');
INSERT INTO alternatif (id, nama) VALUES (49, 'Karyawan 49');
INSERT INTO alternatif (id, nama) VALUES (50, 'Karyawan 50');
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 19, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (1, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 15, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (2, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (3, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 15, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (4, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 16, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 19, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (5, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 19, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (6, 20, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 15, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (7, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (8, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (9, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (10, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (11, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 15, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 16, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (12, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (13, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (14, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (15, 20, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (16, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (17, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (18, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (19, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (20, 20, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 15, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (21, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (22, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 19, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (23, 20, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (24, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 16, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (25, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (26, 20, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 16, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (27, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (28, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (29, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (30, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (31, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (32, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (33, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (34, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 15, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (35, 20, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 16, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (36, 20, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (37, 20, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 16, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 17, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (38, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (39, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (40, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 15, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 19, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (41, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (42, 20, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 19, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (43, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 15, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (44, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 17, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (45, 20, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 18, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 19, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (46, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 14, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 16, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (47, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 15, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 18, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (48, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 14, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 17, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 18, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 19, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (49, 20, '3', 3);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 14, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 15, '4', 4);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 16, '2', 2);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 17, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 18, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 19, '1', 1);
INSERT INTO penilaian (alternatif_id, kriteria_id, nilai_input, nilai_angka) VALUES (50, 20, '3', 3);